#!/bin/bash
# Commandes immédiates à exécuter pour corriger le problème NaN

echo "🔴 DIAGNOSTIC COMPLET TERMINÉ"
echo "=============================="
echo ""
echo "📋 FICHIERS À LIRE (dans cet ordre):"
echo "1. RESUME_DIAGNOSTIC_COMPLET.md ← COMMENCER ICI"
echo "2. DIAGNOSTIC_FINAL.md"
echo "3. PLAN_ACTION_IMMEDIAT.md"
echo ""

echo "🚨 PROBLÈME CRITIQUE IDENTIFIÉ:"
echo "==============================="
echo "❌ 4.5 MILLIONS d'erreurs NaN dans les logs"
echo "❌ Workers W1, W2, W3 crashent"
echo "❌ Entraînement bloqué"
echo ""

echo "⏹️  ÉTAPE 1: ARRÊTER L'ENTRAÎNEMENT"
echo "===================================="
echo "Exécuter:"
echo ""
echo "  pkill -f train_parallel_agents.py"
echo "  sleep 5"
echo ""
echo "Puis vérifier:"
echo "  ps aux | grep train_parallel | grep -v grep"
echo ""

echo "🔍 ÉTAPE 2: IDENTIFIER LA SOURCE DES NaN"
echo "========================================="
echo "Exécuter:"
echo ""
echo "  # Voir les erreurs NaN"
echo "  grep -i 'nan\|inf' /mnt/new_data/adan_logs/training_*.log | head -20"
echo ""
echo "  # Analyser les logs"
echo "  bash /home/morningstar/Documents/trading/bot/quick_log_analysis.sh"
echo ""

echo "🛠️  ÉTAPE 3: CORRIGER LES NaN"
echo "=============================="
echo "À faire:"
echo "1. Ajouter clipping aux observations (state_builder.py)"
echo "2. Ajouter clipping aux récompenses (reward_calculator.py)"
echo "3. Vérifier les scalers (safe_scaler_wrapper.py)"
echo "4. Remplacer NaN par 0 avec np.nan_to_num()"
echo ""
echo "Voir DIAGNOSTIC_FINAL.md pour les détails"
echo ""

echo "✅ ÉTAPE 4: VALIDER LES CORRECTIONS"
echo "===================================="
echo "Exécuter:"
echo ""
echo "  cd /home/morningstar/Documents/trading/bot"
echo "  timeout 300 python scripts/train_parallel_agents.py \\"
echo "    --config-path config/config.yaml \\"
echo "    --checkpoint-dir checkpoints \\"
echo "    --resume \\"
echo "    2>&1 | tee test_100_steps.log &"
echo ""
echo "Puis vérifier après 100 steps:"
echo "  grep -i 'nan\|error' test_100_steps.log | wc -l"
echo ""

echo "🚀 ÉTAPE 5: RELANCER L'ENTRAÎNEMENT"
echo "===================================="
echo "Exécuter:"
echo ""
echo "  cd /home/morningstar/Documents/trading/bot"
echo "  timeout 86400 python scripts/train_parallel_agents.py \\"
echo "    --config-path config/config.yaml \\"
echo "    --checkpoint-dir checkpoints \\"
echo "    --resume \\"
echo "    2>&1 | tee /mnt/new_data/adan_logs/training_\$(date +%Y%m%d_%H%M%S).log &"
echo ""

echo "📊 DURÉE ESTIMÉE"
echo "================"
echo "Étape 1 (Arrêter): 5 min"
echo "Étape 2 (Identifier): 30 min"
echo "Étape 3 (Corriger): 1-2h"
echo "Étape 4 (Valider): 30 min"
echo "Étape 5 (Relancer): 30 min"
echo "TOTAL: 2-3 heures"
echo ""

echo "✅ DIAGNOSTIC TERMINÉ"
echo "===================="
echo "Prochaine action: Lire RESUME_DIAGNOSTIC_COMPLET.md"
echo ""
