# Configuration des Données pour ADAN 1.1

# Liste des actifs à trader (ADAN 1.1 - 5 cryptomonnaies)
assets: ["BTCUSDT", "ETHUSDT", "BNBUSDT", "ADAUSDT", "XRPUSDT"]

# Timeframes à utiliser
timeframes: ["1m"]

# Configuration du CNN
cnn_input_window_size: 20  # Taille de la fenêtre temporelle pour le CNN

# Configuration détaillée du CNN pour l'extracteur de caractéristiques
cnn_config:
  features_dim: 64  # Dimension de sortie de l'extracteur de caractéristiques
  num_input_channels: 1  # Nombre de canaux d'entrée (1 pour données 2D)
  conv_layers:  # Configuration des couches convolutives
    - out_channels: 32
      kernel_size: 3
      stride: 1
      padding: 1
    - out_channels: 64
      kernel_size: 3
      stride: 1
      padding: 1
  pool_layers:  # Configuration des couches de pooling
    - kernel_size: 2
      stride: 2
    - kernel_size: 2
      stride: 2
  activation: "relu"  # Fonction d'activation (relu, leaky_relu, etc.)
  dropout: 0.2  # Taux de dropout pour régularisation
  fc_layers: [64]  # Couches fully connected avant la sortie

# Timeframe principal pour l'entraînement
training_timeframe: "1m"  # Timeframe à utiliser pour l'entraînement

# Liste des timeframes à traiter
timeframes_to_process: ["1m"]

# ADAN 1.1: Features directement disponibles dans les données combined
# Ces noms correspondent exactement aux colonnes dans combined_*.parquet
base_market_features: [
  # Prix OHLCV
  "open", "high", "low", "close", "volume",
  
  # Moyennes mobiles
  "SMA_short", "SMA_long", "EMA_short", "EMA_long",
  
  # Oscillateurs
  "RSI", "STOCHk", "STOCHd", "STOCHRSIk",
  
  # MACD
  "MACD", "MACDs", "MACDh",
  
  # Bollinger Bands
  "BBU", "BBM", "BBL",
  
  # Volatilité et Tendance
  "ATR", "ADX",
  
  # Momentum
  "CCI", "Momentum", "ROC", "Williams_%R",
  
  # Indicateurs avancés
  "Ultimate_Osc", "OBV", "VWMA", "CMF", "MFI",
  
  # Support/Résistance
  "Parabolic_SAR", "VWAP",
  
  # Autres indicateurs
  "PPO", "CMO"
]

# Périodes de téléchargement par timeframe
timeframe_periods:
  "1m":
    start_date: "2024-01-01"
    end_date: "2025-02-01"

# Date de début par défaut pour le téléchargement des données
default_fetch_start_date: "2024-01-01"

# Répertoires de données
raw_data_dir: "raw"
processed_data_dir: "processed"
scalers_encoders_dir: "scalers_encoders"

# Split des données pour l'entraînement/validation/test
data_split:
  "1m":
    train_start_date: "2024-01-01"
    train_end_date: "2024-10-05"
    validation_start_date: "2024-10-05"
    validation_end_date: "2024-12-04"
    test_start_date: "2024-12-04"
    test_end_date: "2025-02-01"
  validation_percentage: 0.15

# Prétraitement des données
preprocessing:
  missing_values: "fill_forward"
  outlier_treatment: "clip"
  outlier_threshold: 3.0
  time_alignment: true
  resampling: "none"

# Features à normaliser (ADAN 1.1 - déjà normalisées)
features_to_normalize: []

# Méthode de gestion des valeurs manquantes
missing_values_handling: "ffill"

# Paramètres pour le calcul des rendements
returns:
  type: "log_return"
  periods: [1, 5, 10]

# Normalisation des données (ADAN 1.1 - déjà effectuée)
normalization:
  method: "standard"
  scope: "feature"
  window_size: 0
  save_scalers: true
  scalers_path: "../data/scalers_encoders/"

# Division des données (ADAN 1.1 - déjà effectuée)
data_split:
  method: "chronological"
  train_ratio: 0.7
  validation_ratio: 0.15
  test_ratio: 0.15
  random_seed: 42
  cv_folds: 5
  window_size_days: 180