reward:
  type: "percentage"
  scale: 1.0
  penalty_scale: 1.0
  profit_target: 0.02
  stop_loss: 0.01
  position_holding: 0.001
  profit_target: 0.02
  stop_loss: 0.01
  profit_target: 0.02
  stop_loss: 0.01
learning:
  ent_coef_range:
  - 0.001
  - 0.1
  gamma_range:
  - 0.9
  - 0.999
  learning_rate_range:
  - 1e-5
  - 1e-3
logging:
  compression: gzip
  log_dir: logs/dbe
  log_level: INFO
modes:
  bear:
    position_size_multiplier: 0.8
    sl_multiplier: 1.1
    tp_multiplier: 0.9
  bull:
    position_size_multiplier: 1.1
    sl_multiplier: 0.9
    tp_multiplier: 1.2
  sideways:
    position_size_multiplier: 0.9
    sl_multiplier: 0.8
    tp_multiplier: 0.8
  volatile:
    position_size_multiplier: 0.7
    sl_multiplier: 1.3
    tp_multiplier: 0.8
position_sizing:
  base_position_size: 0.1
  max_position_size: 0.3
  min_position_size: 0.01
risk_parameters:
  base_sl_pct: 0.02
  base_tp_pct: 0.04
  drawdown_risk_multiplier: 2.0
  max_sl_pct: 0.1
  min_sl_pct: 0.005
  volatility_impact: 1.5
smoothing_factor: 0.1
state_persistence:
  enabled: true
  save_interval: 100
  save_path: logs/dbe/state
