# Configuration du Logging pour ADAN (format dictConfig)
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/adan.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    encoding: utf-8
  
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    encoding: utf-8

# Configuration des loggers spécifiques
loggers:
  adan_trading_bot:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: no
  
  adan_trading_bot.data_processing:
    level: INFO
    handlers: [console, file_handler]
    propagate: no
  
  adan_trading_bot.environment:
    level: INFO
    handlers: [console, file_handler]
    propagate: no
  
  adan_trading_bot.training:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, error_file_handler]
  propagate: no
