batch_size: 16
clip_range: 0.2
device: cpu
ent_coef: 0.0
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0003
n_epochs: 1
n_steps: 10
policy: MlpPolicy
total_timesteps: 50000
n_envs: 1
_envs: 1
verbose: 1
