data_pipeline:
  local_data:
    directory: data/raw

data_sources:
  - name: binance
    type: exchange
    assets: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "XRP/USDT", "ADA/USDT"]

feature_engineering:
  timeframes: ["4h", "1h", "5m"] # Processing order as required
  features:
    "5m":
      - "open"
      - "high" 
      - "low"
      - "close"
      - "volume"
      - "minutes_since_update"
    "1h":
      - "open"
      - "high"
      - "low" 
      - "close"
      - "volume"
      - "minutes_since_update"
    "4h":
      - "open"
      - "high"
      - "low"
      - "close" 
      - "volume"
      - "minutes_since_update"

indicators:
  - "EMA_10"
  - "EMA_20"
  - "EMA_50"
  - "EMA_100"
  - "EMA_200"
  - "RSI_14"
  - "RSI_21"
  - "RSI_28"
  - "MACD"
  - "ATR_14"
  - "ATR_20"
  - "ATR_28"
  - "BBANDS_20"
  - "BBANDS_50"
  - "BBANDS_100"
  - "STOCH_5_3_3"
  - "STOCH_14_3_3"
  - "WILLR_14"
  - "WILLR_21"
  - "CCI_14"
  - "CCI_20"
  - "ADX_14"
  - "ADX_20"
  - "ADX_28"
  - "SAR_0.02_0.2"
  - "OBV"
  - "VWAP"
  - "Ichimoku_Cloud"

indicators_by_timeframe:
  "5m":
    - "EMA_10"
    - "EMA_20"
    - "RSI_14"
    - "MACD"
    - "ATR_14"
    - "BBANDS_20"
    - "STOCH_5_3_3"
    - "WILLR_14"
    - "CCI_14"
    - "ADX_14"
    - "SAR_0.02_0.2"
    - "OBV"
    - "VWAP"
  "1h":
    - "EMA_50"
    - "EMA_100"
    - "RSI_21"
    - "MACD"
    - "ATR_20"
    - "BBANDS_50"
    - "STOCH_14_3_3"
    - "WILLR_21"
    - "CCI_20"
    - "ADX_20"
    - "SAR_0.02_0.2"
    - "OBV"
    - "VWAP"
  "4h":
    - "EMA_200"
    - "RSI_28"
    - "MACD"
    - "ATR_28"
    - "BBANDS_100"
    - "Ichimoku_Cloud"
    - "ADX_28"
    - "SAR_0.02_0.2"
    - "OBV"
    - "VWAP"