# ==============================================================================
# CONFIGURATION DE L'ENVIRONNEMENT DE TRADING
# ==============================================================================
# Ce fichier définit le comportement de l'environnement de simulation, y compris
# le capital initial, les règles de trading, la gestion des risques et les récompenses.

# ------------------------------------------------------------------------------
# Paramètres Généraux
# ------------------------------------------------------------------------------
mode: "backtest" # Modes possibles: "backtest", "paper", "live"
initial_capital: 20.0 # Capital de départ en USDT
base_currency: "USDT"

data_pipeline:
  type: "csv"
  path: "data/raw/BTCUSDT_1m.csv"
  features: ["close", "volume"]
  target: "close"
  ccxt_download:
    symbol: "BTC/USDT"
  feature_engineering:
    timeframes: ["1h"]
    indicators:
      - type: "ema"
        period: 9
      - type: "ema"
        period: 21
      - type: "rsi"
        period: 14
    fillna: true

feature_engineering:
  timeframes: ["5m", "1h", "4h"]
  indicators:
    # Indicateurs de tendance
    - type: "sma"
      period: 20
    - type: "ema"
      period: 9
    - type: "ema"
      period: 21
    - type: "ema"
      period: 50
    - type: "ema"
      period: 200
    - type: "macd"
      fast: 12
      slow: 26
      signal: 9
    # Indicateurs de momentum
    - type: "rsi"
      period: 14
    - type: "stoch"
      k: 14
      d: 3
      smooth_k: 3
    - type: "cci"
      period: 20
    - type: "adx"
      period: 14
    - type: "williams"
      period: 14
    # Indicateurs de volatilité
    - type: "bbands"
      period: 20
      std: 2.0
    - type: "atr"
      period: 14
    # Indicateurs de volume
    - type: "obv"
    - type: "vwap"
    - type: "mfi"
      period: 14
  fillna: true
  columns_to_normalize: ["open", "high", "low", "close", "volume"]

# ------------------------------------------------------------------------------
# Section imbriquée pour compatibilité legacy
# ------------------------------------------------------------------------------
environment:
  initial_capital: 100.0
  base_currency: "USDT"
  trading_rules:
    min_order_value_usdt: 10.0
    min_remaining_capital_usdt: 1.0
    max_leverage: 10
    commission_pct: 0.0004
    slippage_pct: 0.0005
  chunk_size:
    "5m": 500
    "1h": 500
    "4h": 49
  feature_engineering:
    timeframes: ["1m"]
    indicators:
      - type: "ema"
        period: 9
      - type: "ema"
        period: 21
      - type: "rsi"
        period: 14
    fillna: true
# ------------------------------------------------------------------------------
# Configuration de l'Échange (pour paper/live trading)
# ------------------------------------------------------------------------------
exchange:
  id: "binance"
  use_testnet: true
  api_key: "${BINANCE_API_KEY}" # Utilise des variables d'environnement
  api_secret: "${BINANCE_API_SECRET}"
  options:
    defaultType: "future"
    adjustForTimeDifference: true
    recvWindow: 60000

# ------------------------------------------------------------------------------
# Règles de Trading Fondamentales
# ------------------------------------------------------------------------------
trading_rules:
  # Valeur minimale d'un ordre requise par l'échange (ex: 10 USDT pour Binance)
  min_order_value_usdt: 10.0

  # Capital minimum à conserver en permanence. L'agent ne peut pas passer
  # un ordre qui ferait passer le solde disponible sous ce seuil.
  min_remaining_capital_usdt: 1.0

  # Effet de levier maximum autorisé
  max_leverage: 10

  # Frais de transaction en pourcentage (0.04% pour Taker sur Binance Futures)
  commission_pct: 0.0004

  # Slippage simulé en pourcentage pour les backtests
  slippage_pct: 0.0005

# ------------------------------------------------------------------------------
# Paliers de Capital et Allocation de Risque (Gestion des Petits Capitaux)
# ------------------------------------------------------------------------------
# Le système ajuste dynamiquement sa stratégie de trading en fonction du capital
# total. C'est une règle de survie essentielle pour les petits portefeuilles.

# Format simplifié pour PortfolioManager
capital_tiers:
  - threshold: 0 # Tier 1 – Micro Capital
    max_position_size: 0.20 # 20% du capital (allocation_frac_range [0.95,1.0])
  - threshold: 30 # Tier 2 – Small Capital
    max_position_size: 0.20 # 20%
  - threshold: 100 # Tier 3 – Medium Capital
    max_position_size: 0.20 # 20%
  - threshold: 300 # Tier 4 – High Capital
    max_position_size: 0.20 # 20%
  - threshold: 1000 # Tier 5 – Enterprise
    max_position_size: 0.20 # 20%

# Configuration complète des paliers avec tous les paramètres
tiers:
  - name: Tier1_Micro
    threshold: 0
    min_order_value: 10.0
    reserve_fraction: 0.05
    allocation_frac: [0.95, 1.0]
    max_positions: 1
    fee_multiplier: 2.5
  - name: Tier2_Small
    threshold: 30
    min_order_value: 50.0
    reserve_fraction: 0.05
    allocation_frac: [0.90, 1.0]
    max_positions: 2
    fee_multiplier: 2.0
  - name: Tier3_Medium
    threshold: 100
    min_order_value: 100.0
    reserve_fraction: 0.05
    allocation_frac: [0.80, 1.0]
    max_positions: 3
    fee_multiplier: 1.5
  - name: Tier4_High
    threshold: 300
    min_order_value: 200.0
    reserve_fraction: 0.05
    allocation_frac: [0.70, 1.0]
    max_positions: 4
    fee_multiplier: 1.2
  - name: Tier5_Enterprise
    threshold: 1000
    min_order_value: 500.0
    reserve_fraction: 0.05
    allocation_frac: [0.50, 1.0]
    max_positions: 5
    fee_multiplier: 1.0

# ------------------------------------------------------------------------------
# Modulation du risque DBE (Sprint 5)
# ------------------------------------------------------------------------------
risk_modulation:
  drawdown_threshold_defensif: 15.0 # Seuil augmenté pour passage en mode défensif (était 12.0)
  drawdown_threshold_agressif: 5.0 # Seuil ajusté pour mode agressif (était 7.0)
  drawdown_sl_factor: 0.75 # Facteur de stop-loss plus agressif (nouveau paramètre)
  aggressive_mode_winrate_trigger: 0.60 # Nouveau paramètre: Seuil de winrate pour le mode agressif

# ------------------------------------------------------------------------------
# Pénalités et Récompenses (Shaping de la Récompense)
# ------------------------------------------------------------------------------
# Ces paramètres façonnent le signal de récompense pour guider l'agent vers
# un comportement souhaitable.

penalties:
  # Pénalité pour une action invalide (ex: essayer d'ouvrir trop de positions).
  # Cela apprend à l'agent à respecter les règles de l'environnement.
  invalid_action: -0.1

  # Pénalité si un ordre est rejeté par l'échange (ex: fonds insuffisants).
  # Plus sévère car cela indique une mauvaise gestion du capital.
  order_rejection: -0.5

  # Paramètres d'inaction révisés
  inaction_freq_threshold: 0.15 # Seuil de fréquence d'inaction (15%)
  inaction_pnl_threshold: 0.05 # Seuil de PnL pour l'inaction
  base_inaction_penalty: -0.001 # Pénalité de base réduite (était -0.00005)

reward_shaping:
  # Multiplicateurs de récompense
  realized_pnl_multiplier: 1.0 # Multiplicateur pour le PnL réalisé
  unrealized_pnl_multiplier: 0.1 # Multiplicateur pour le PnL latent

  # Paramètres d'inaction
  inaction_penalty: -0.001 # Pénalité d'inaction légèrement augmentée

  # Contrôle des valeurs de récompense
  reward_clipping_range: [-3.0, 3.0] # Plage réduite pour des mises à jour plus stables

  # Configuration des chunks
  optimal_trade_bonus: 2.0 # Bonus maximal légèrement réduit
  performance_threshold: 0.6 # Seuil de performance augmenté (moins de faux positifs)
  chunk_size: 2000 # Taille de chunk inchangée

  # Configuration de l'apprentissage
  use_ewc: true # Conserver l'EWC activé
  ewc_lambda: 0.2 # Poids EWC augmenté pour une meilleure rétention

  # Configuration de la mémoire de rejeu
  use_prioritized_replay: true
  prioritized_replay_alpha: 0.6
  prioritized_replay_beta: 0.4
  prioritized_replay_eps: 1e-6

# ------------------------------------------------------------------------------
# Paramètres de l'environnement
# ------------------------------------------------------------------------------
environment_parameters:
  volatility_threshold_high: 0.03
  volatility_threshold_low: 0.01
  adx_threshold: 25.0
  ema_ratio_threshold: 1.005
  atr_pct_threshold: 0.02
