# Configuration avancée du feature engineering pour ADAN - 22+ indicateurs par timeframe
feature_engineering:
  # Timeframes à utiliser pour le traitement
  timeframes: ["5m", "1h", "4h"]
  
  # Configuration des 22+ indicateurs techniques par timeframe
  # Utilise maintenant AdvancedIndicatorCalculator pour calcul automatique
  indicators:
    # Indicateurs de Tendance (7 indicateurs)
    trend:
      - "SMA_10"    # Simple Moving Average 10
      - "SMA_20"    # Simple Moving Average 20  
      - "SMA_50"    # Simple Moving Average 50
      - "EMA_12"    # Exponential Moving Average 12
      - "EMA_26"    # Exponential Moving Average 26
      - "MACD"      # MACD Line
      - "MACD_Signal" # MACD Signal Line
    
    # Indicateurs de Momentum (6 indicateurs)
    momentum:
      - "RSI"       # Relative Strength Index
      - "STOCH_K"   # Stochastic %K
      - "STOCH_D"   # Stochastic %D
      - "WILLR"     # Williams %R
      - "CCI"       # Commodity Channel Index
      - "ADX"       # Average Directional Index
    
    # Indicateurs de Volatilité (4 indicateurs)
    volatility:
      - "ATR"       # Average True Range
      - "BB_Upper"  # Bollinger Band Upper
      - "BB_Lower"  # Bollinger Band Lower
      - "BB_Middle" # Bollinger Band Middle
    
    # Indicateurs de Volume (5 indicateurs)
    volume:
      - "OBV"         # On Balance Volume
      - "VWAP"        # Volume Weighted Average Price
      - "MFI"         # Money Flow Index
      - "Volume_SMA"  # Volume Simple Moving Average
      - "Volume_Ratio" # Volume Ratio
  
  # Colonnes à normaliser (mise à jour pour inclure tous les nouveaux indicateurs)
  columns_to_normalize:
    # Prix de base
    - "open"
    - "high" 
    - "low"
    - "close"
    - "volume"
    # Indicateurs de tendance
    - "SMA"
    - "EMA"
    - "MACD"
    # Indicateurs de momentum
    - "RSI"
    - "STOCH"
    - "WILLR"
    - "CCI"
    - "ADX"
    # Indicateurs de volatilité
    - "ATR"
    - "BB"
    # Indicateurs de volume
    - "OBV"
    - "VWAP"
    - "MFI"
    - "Volume"
  
  # Options de traitement
  preprocessing:
    fillna: true  # Remplir les valeurs manquantes
    normalize: true  # Normaliser les caractéristiques
    remove_outliers: true  # Supprimer les valeurs aberrantes
    min_data_points: 50  # Minimum de points pour calculer les indicateurs
    
  # Paramètres de performance
  performance:
    chunk_size: 10000  # Taille des lots pour le traitement par lots
    n_jobs: -1  # Utiliser tous les cœurs CPU disponibles
    cache_indicators: true  # Cache intelligent des calculs
    parallel_timeframes: true  # Paralléliser calculs multi-timeframes
    
  # Validation des features
  validation:
    check_nan_percentage: true  # Vérifier le pourcentage de NaN
    max_nan_percentage: 0.05  # Maximum 5% de NaN autorisé
    check_feature_correlation: true  # Vérifier corrélation entre features
    max_correlation_threshold: 0.95  # Seuil de corrélation maximum
