# Configuration du Logging pour ADAN - Version 3.1 (format dictConfig)
version: 1
disable_existing_loggers: false

# Configuration des répertoires de logs
log_dirs:
  base: "logs"
  dbe_replay: "logs/dbe_replay"  # Répertoire pour les logs du ReplayLogger
  metrics: "logs/metrics"
  models: "logs/models"
  performance: "logs/performance"  # Logs de performance selon le design
  data_quality: "logs/data_quality"  # Logs de qualité des données
  memory: "logs/memory"  # Logs de monitoring mémoire

# Définition des formats de log
formatters:
  # Format standard pour la console
  standard:
    format: "%(asctime)s - %(name)-25s - %(levelname)-8s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  # Format détaillé pour les fichiers
  detailed:
    format: "%(asctime)s - %(name)-25s - %(levelname)-8s - %(filename)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    
  # Format JSON pour l'analyse structurée
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(filename)s %(lineno)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

# Gestionnaires de logs
handlers:
  # Console (sortie standard)
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  # Fichier de log principal
  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/adan.log
    when: 'midnight'  # Rotation quotidienne
    backupCount: 30    # Conserver 30 jours de logs
    encoding: utf-8
    utc: True  # Utiliser UTC pour éviter les problèmes de changement d'heure
  
  # Fichier d'erreurs
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10 MB
    backupCount: 10
    encoding: utf-8
  
  # Fichier de log structuré en JSON
  json_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/adan_structured.log
    maxBytes: 10485760  # 10 MB
    backupCount: 10
    encoding: utf-8
  
  # Handler spécialisé pour les métriques de performance
  performance_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/performance/performance.log
    when: 'H'  # Rotation horaire pour les métriques
    backupCount: 168  # 7 jours d'historique
    encoding: utf-8
  
  # Handler pour la qualité des données
  data_quality_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/data_quality/data_quality.log
    maxBytes: 5242880  # 5 MB
    backupCount: 5
    encoding: utf-8
  
  # Handler pour le monitoring mémoire
  memory_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/memory/memory.log
    when: 'M'  # Rotation par minute pour monitoring intensif
    backupCount: 1440  # 24 heures d'historique
    encoding: utf-8

# Configuration des loggers spécifiques
loggers:
  # Logger racine
  '':
    level: WARNING
    handlers: [console, file_handler, error_file_handler]
    propagate: no
  
  # Logger principal de l'application
  adan:
    level: INFO
    handlers: [console, file_handler, json_file_handler]
    propagate: no
  
  # Loggers pour les différents modules
  adan.data:
    level: INFO
    handlers: [file_handler, json_file_handler]
    propagate: no
  
  adan.models:
    level: INFO
    handlers: [file_handler, json_file_handler]
    propagate: no
  
  adan.training:
    level: DEBUG
    handlers: [file_handler, json_file_handler]
    propagate: no
  
  adan.trading:
    level: INFO
    handlers: [console, file_handler, json_file_handler]
    propagate: no
  
  # Loggers spécialisés pour le monitoring détaillé selon le design
  adan.data_processing.chunked_loader:
    level: DEBUG
    handlers: [file_handler, performance_handler, data_quality_handler]
    propagate: no
  
  adan.data_processing.performance:
    level: DEBUG
    handlers: [performance_handler]
    propagate: no
  
  adan.data_processing.memory:
    level: DEBUG
    handlers: [memory_handler]
    propagate: no
  
  adan.data_processing.quality:
    level: INFO
    handlers: [data_quality_handler, file_handler]
    propagate: no
  
  adan.environment.multi_asset_env:
    level: DEBUG
    handlers: [file_handler, performance_handler]
    propagate: no
  
  adan.environment.memory:
    level: DEBUG
    handlers: [memory_handler]
    propagate: no
  
  # Loggers pour les dépendances
  tensorflow:
    level: WARNING
    handlers: [file_handler]
    propagate: no
    
  stable_baselines3:
    level: INFO
    handlers: [file_handler]
    propagate: no
    
  urllib3:
    level: WARNING
    handlers: [file_handler]
    propagate: no
  
  # Logger pour PyArrow (utilisé par les fichiers parquet)
  pyarrow:
    level: WARNING
    handlers: [file_handler]
    propagate: no

# Configuration du niveau de log racine
root:
  level: WARNING
  handlers: [console, file_handler, error_file_handler]
  propagate: no
