# ==============================================================================
# CONFIGURATION PRINCIPALE DU PROJET ADAN
# ==============================================================================
# Ce fichier est le point d'entrée de la configuration. Il charge et orchestre
# les autres fichiers de configuration spécifiques (données, environnement, agent).

# Configuration des données
data:
  # Répertoire des données
  data_dir: "/home/morningstar/Documents/trading/ADAN/data/final"
  
  # Paires de trading disponibles (5 paires majeures)
  assets: 
    - "BTC"    # Bitcoin - La cryptomonnaie la plus importante par capitalisation
    - "ETH"    # Ethereum - La deuxième plus grande cryptomonnaie
    - "SOL"    # Solana - Une blockchain performante et populaire
    - "XRP"    # Ripple - Une cryptomonnaie de paiement majeure
    - "ADA"    # Cardano - Une plateforme de contrats intelligents concurrente d'Ethereum
  
  # Timeframes disponibles (du plus court au plus long)
  timeframes: ["5m", "1h", "4h"]
  # Configuration des caractéristiques par timeframe  features_per_timeframe:    "5m":      - "OPEN"      - "HIGH"      - "LOW"      - "CLOSE"      - "VOLUME"      - "RSI_14"      - "STOCHk_14_3_3"      - "STOCHd_14_3_3"      - "CCI_20_0.015"      - "ROC_9"      - "MFI_14"      - "EMA_5"      - "EMA_20"    "1h":      - "OPEN"      - "HIGH"      - "LOW"      - "CLOSE"      - "VOLUME"      - "RSI_14"      - "STOCHk_14_3_3"      - "STOCHd_14_3_3"      - "CCI_20_0.015"      - "ROC_9"      - "MFI_14"      - "EMA_5"      - "EMA_20"    "4h":      - "OPEN"      - "HIGH"      - "LOW"      - "CLOSE"      - "VOLUME"      - "RSI_14"      - "STOCHk_14_3_3"      - "STOCHd_14_3_3"      - "CCI_20_0.015"      - "ROC_9"      - "MFI_14"      - "EMA_5"      - "EMA_20"
