# ==============================================================================
# CONFIGURATION DE LA GESTION DES RISQUES
# ==============================================================================
# Configuration pour le Dynamic Behavior Engine (DBE) et la gestion des risques

# ------------------------------------------------------------------------------
# Paramètres de Base du DBE
# ------------------------------------------------------------------------------
dbe_settings:
  # Modes de risque disponibles
  risk_modes:
    - "NORMAL"
    - "DEFENSIVE" 
    - "AGGRESSIVE"
  
  # Mode par défaut au démarrage
  default_mode: "NORMAL"
  
  # Seuils de transition entre modes
  mode_thresholds:
    defensive: 0.7    # Corrélation > 0.7 ou volatilité élevée
    aggressive: 1.2   # Performance > 1.2x moyenne
  
  # Seuil de corrélation critique
  correlation_threshold: 0.7
  
  # Cible de volatilité
  volatility_target: 0.02

# ------------------------------------------------------------------------------
# Métriques de Risque
# ------------------------------------------------------------------------------
risk_metrics:
  # Value at Risk (VaR)
  var:
    confidence_level: 0.95
    time_horizon_days: 1
    method: "historical"  # "historical", "parametric", "monte_carlo"
  
  # Sharpe Ratio
  sharpe_ratio:
    risk_free_rate: 0.02  # 2% annuel
    target_ratio: 1.0     # Objectif minimum
  
  # Maximum Drawdown
  max_drawdown:
    warning_threshold: 0.15  # 15%
    critical_threshold: 0.25 # 25%
  
  # Volatilité
  volatility:
    window_size: 30
    annualization_factor: 365
    target_volatility: 0.15  # 15% annuel

# ------------------------------------------------------------------------------
# Position Sizing Basé sur les Risques
# ------------------------------------------------------------------------------
position_sizing:
  # Méthode de calcul de la taille des positions
  method: "volatility_adjusted"  # "fixed", "percentage", "volatility_adjusted", "kelly"
  
  # Paramètres pour le sizing basé sur la volatilité
  volatility_sizing:
    target_volatility: 0.02
    lookback_period: 20
    min_position_size: 0.01  # 1% du capital
    max_position_size: 0.20  # 20% du capital
  
  # Paramètres pour la formule de Kelly
  kelly_sizing:
    max_kelly_fraction: 0.25  # Limite à 25% de Kelly
    confidence_adjustment: 0.5 # Facteur de prudence
  
  # Limites de concentration
  concentration_limits:
    max_single_asset: 0.30    # 30% max par actif
    max_correlated_assets: 0.50 # 50% max pour actifs corrélés

# ------------------------------------------------------------------------------
# Gestion des Stop-Loss et Take-Profit
# ------------------------------------------------------------------------------
stop_loss_take_profit:
  # Stop-Loss dynamique
  stop_loss:
    base_pct: 0.02           # 2% de base
    volatility_multiplier: 1.5 # Ajustement selon volatilité
    trailing_enabled: true
    trailing_distance: 0.01   # 1% de distance pour trailing
  
  # Take-Profit dynamique
  take_profit:
    base_pct: 0.04           # 4% de base
    volatility_multiplier: 2.0 # Ajustement selon volatilité
    partial_profit_enabled: true
    partial_profit_levels:
      - level: 0.02          # 2%
        percentage: 0.50     # Fermer 50%
      - level: 0.03          # 3%
        percentage: 0.30     # Fermer 30% supplémentaire

# ------------------------------------------------------------------------------
# Corrélation et Diversification
# ------------------------------------------------------------------------------
correlation_management:
  # Calcul de corrélation
  correlation_window: 30
  correlation_threshold: 0.7
  
  # Actions en cas de forte corrélation
  high_correlation_actions:
    - "reduce_position_size"
    - "limit_new_positions"
    - "increase_diversification"
  
  # Matrice de corrélation des actifs
  asset_correlations:
    update_frequency: "daily"
    min_observations: 20

# ------------------------------------------------------------------------------
# Gestion des Drawdowns
# ------------------------------------------------------------------------------
drawdown_management:
  # Seuils de drawdown
  thresholds:
    warning: 0.10      # 10% - Mode défensif
    critical: 0.20     # 20% - Arrêt temporaire
    emergency: 0.30    # 30% - Arrêt complet
  
  # Actions par niveau de drawdown
  actions:
    warning:
      - "reduce_position_sizes"
      - "increase_stop_loss_sensitivity"
    critical:
      - "close_risky_positions"
      - "pause_new_trades"
    emergency:
      - "close_all_positions"
      - "stop_trading"

# ------------------------------------------------------------------------------
# Monitoring et Alertes
# ------------------------------------------------------------------------------
monitoring:
  # Fréquence de calcul des métriques
  calculation_frequency: "1h"
  
  # Alertes activées
  alerts_enabled: true
  
  # Seuils d'alerte
  alert_thresholds:
    high_volatility: 0.05     # 5%
    high_correlation: 0.8     # 80%
    large_drawdown: 0.15      # 15%
    low_sharpe: 0.5           # Sharpe < 0.5
  
  # Historique des métriques
  metrics_history:
    retention_days: 90
    save_frequency: "1h"

# ------------------------------------------------------------------------------
# Paramètres Avancés
# ------------------------------------------------------------------------------
advanced_settings:
  # Régularisation EWC pour l'apprentissage continu
  ewc:
    enabled: true
    lambda: 0.1
    importance_calculation: "fisher"
  
  # Adaptation dynamique des paramètres
  dynamic_adaptation:
    enabled: true
    adaptation_frequency: "daily"
    learning_rate: 0.01
  
  # Backtesting des stratégies de risque
  risk_backtesting:
    enabled: true
    lookback_period: 30
    rebalancing_frequency: "weekly"