trading:
  enabled: false
  exchange: 'binance'
  symbol: 'BTC/USDT'
  leverage: 1
  max_drawdown: 0.2
  stop_loss: 0.1
  take_profit: 0.3
  futures_enabled: false
  futures_commission_pct: 0.0004 # 0.04% for taker
  funding_rate_consideration: true
  min_trade_size: 0.0001 # Minimum quantity of asset to trade
  min_notional_value: 10.0 # Minimum value of an order in USDT
  max_notional_value: 100000.0 # Maximum value of an order in USDT
  liquidation_threshold: 0.05 # Margin level below which liquidation occurs (e.g., 5%)
