# config/training_prod.yaml
training:
  total_timesteps: 1000000
  batch_size:        64
  n_steps:           2048
  n_epochs:          10
  learning_rate:     3e-4
  ent_coef:          0.01
  vf_coef:           0.5
  clip_range:        0.2
  gamma:             0.99
  gae_lambda:        0.95
